name: Build Kernel

permissions:
  contents: write
  actions: write

on:
  workflow_call:

jobs:
  # Realme
  build-realme-5-pro:
    name: "Realme 5 Pro (Based LineageOS)"
    strategy:
      fail-fast: true
    uses: ./.github/workflows/build-realme-5-pro.yml
    secrets: inherit
